### ISSUE TITLE
Latest version items not rendering

### ISSUE THREAD

**Issue by vinz243** [DarkRoleplay/Dark-Roleplay-Medieval#14]
In the latest version, I am having issues with these items

 - **Firepit**: when placing the fire pit somewhere, the model is invisible, but hovering it will show the bounding box
 - **Lectern**: placing a book (even a drp book) on the lectern does nothing
 - **Rope Fence**: randomly crash once placed (or just having it in my hand)
```
[17:45:25] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:92) ~[bvo.class:?]
	at net.dark_roleplay.drpcore.client.events.rendering.Event_BlockHighlight.highlightGhostBlock(Event_BlockHighlight.java:96) ~[Event_BlockHighlight.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_Event_BlockHighlight_highlightGhostBlock_DrawBlockHighlightEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:163) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at Reflector.callBoolean(Reflector.java:656) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1805) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1611) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1382) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.dark_roleplay.medieval.client.model_baking.DelayedBaker_RopeFence.func_188616_a(DelayedBaker_RopeFence.java:91) ~[DelayedBaker_RopeFence.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:142) ~[bvo.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:76) ~[bvo.class:?]
	... 21 more
```
 - **Planks**: cannot place anythng
 - **Wooden lock and keys**: how to use?

**Comment by Luka-HS** [comment]
Planks: They aren't supposed to be placeable (right now), they are just a crafting item.

Wooden lock & key: They aren't fully implemented yet. 
You can use them by changing their NBT though you can lock everything (even normal blocks, with them)

Lectern: I disabled it iirc, because of the limits write able books in vanilla cause.
It is planed that you can read books on it, vanilla books don't allow me to do that.

Firepit: yeah that's a known bug, though it was reported to late that I could fix it with my limited knowledge of git D:

The Rope fence thing is strange 🤔 It's not really caused by the Rope Fence, but more by the placement preview. (This can be disabled in the DRPCore Config).
Thanks for reporting it though! (You are the first to report this)

**Comment by JTK222** [comment]
Planks: They aren't supposed to be placeable (right now), they are just a crafting item.

Wooden lock & key: They aren't fully implemented yet.
You can use them by changing their NBT though you can lock everything (even normal blocks, with them)

Lectern: I disabled it iirc, because of the limits write able books in vanilla cause.
It is planed that you can read books on it, vanilla books don't allow me to do that.

Firepit: yeah that's a known bug, though it was reported to late that I could fix it with my limited knowledge of git D:

The Rope fence thing is strange 🤔 It's not really caused by the Rope Fence, but more by the placement preview. (This can be disabled in the DRPCore Config).
Thanks for reporting it though! (You are the first to report this)

**Comment by vinz243** [comment]
Thanks for the answer, I'll look for future updates!

**Comment by JTK222** [comment]
Fireplace and Rope Fence Issue, will be fixed with the next release.
Not sure about the Wood Lock and Key.
Planks also won't be finished for the next update.

**Comment by JTK222** [comment]
The initial issues are fixed, everything else are suggestions/unfinished features, which we don't need issues for as the mod is still in alpha

**Comment by vinz243** [comment]
Awesome thanks ! when is the next release scheduled ?

**Comment by vinz243** [comment]
The firepite works just fine ! I still can't place anything on the lectern tho and how to use a wooden key ? Thanks
